# Training configuration
training:
  model_name: yolov11n  # Options: yolov11n, yolov11s, yolov11m, yolov11l, yolov11x
  batch_size: 4
  epochs: 1
  img_size: 640
  patience: 50
  workers: 4
  device: 0  # GPU device id, 'cpu' for CPU
  val: true  # Whether to perform validation
  
  # Optimizer settings
  optimizer:
    name: AdamW  # Options: SGD, Adam, AdamW
    lr: 0.001
    weight_decay: 0.0005
    
  # Data augmentation
  augmentation:
    hsv_h: 0.0  
    hsv_s: 0.0  
    hsv_v: 0.0    
    degrees: 0.0  
    translate: 0.0  
    scale: 0.0     
    shear: 0.0     
    flipud: 0.0    
    fliplr: 0.0    
    mosaic: 0.0    
    mixup: 0.0     

# Dataset configuration
dataset:
  data_yaml: "data/datasets/dataset.yaml"  
  cache: False  

# MLflow configuration
mlflow:
  experiment_name: "yolov11-training"
  run_name: null  
  tags:
    version: "v1.0"
    framework: "ultralytics"
    model: "yolo11"
    
# Checkpoint configuration
checkpoint:
  save_best: True
  save_period: 10 